DELETE FROM CAR_PARKING_DETAILS;
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('101', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('102', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('103', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('104', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('105', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('106', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('107', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('108', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('109', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('110', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('111', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('112', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('113', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('114', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('115', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('116', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('117', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('118', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('119', 'Lower Basement', 'Open');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('120', 'Lower Basement', 'Open');

-- Reserved Parking
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('131', 'Lower Basement', 'Reserved');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('132', 'Lower Basement', 'Reserved');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('133', 'Lower Basement', 'Reserved');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('134', 'Lower Basement', 'Reserved');
MERGE INTO CAR_PARKING_DETAILS (CAR_PARKING_ID, PARKING_FLOOR, PARKING_TYPE) VALUES ('135', 'Lower Basement', 'Reserved');
